version: '3'

services:
  # titiler:
  #  container_name: titiler
  #  platform: linux/amd64
  #  build:
  #    context: .
  #    dockerfile: dockerfiles/Dockerfile.uvicorn
  #  ports:
  #    - "8000:8000"
  #  environment:
  #    # Application
  #    - HOST=0.0.0.0
  #    - PORT=8000
  #    # Uvicorn
  #    # http://www.uvicorn.org/settings/#production
  #    - WEB_CONCURRENCY=1
  #    # GDAL config
  #    - CPL_TMPDIR=/tmp
  #    - GDAL_CACHEMAX=75%
  #    - GDAL_INGESTED_BYTES_AT_OPEN=32768
  #    - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
  #    - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
  #    - GDAL_HTTP_MULTIPLEX=YES
  #    - GDAL_HTTP_VERSION=2
  #    - PYTHONWARNINGS=ignore
  #    - VSI_CACHE=TRUE
  #    - VSI_CACHE_SIZE=536870912

  titiler_custom:
    container_name: titiler_custom
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.custom
    ports:
      - "80:80"
    environment:
      # Application
      - HOST=0.0.0.0
      - PORT=80
      # Uvicorn
      # http://www.uvicorn.org/settings/#production
      - WEB_CONCURRENCY=1
      # GDAL config
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_INGESTED_BYTES_AT_OPEN=32768
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
    
  # nginx:
  #  container_name: nginx
  #  image: nginx:latest
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./dockerfiles/nginx_config.conf:/etc/nginx/conf.d/default.conf
  #  depends_on:
  #    - titiler
  #    - titiler_custom
  #  networks:
  #    - default